name: Super-Linter

on: push

jobs:
  test:
    name: Job added for TDS evaluation
    runs-on: ubuntu-latest
    steps:
      - name: 23f2005138@ds.study.iitm.ac.in
        run: echo "Hello, world!"


  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
